#!/usr/bin/env bash
set -euo pipefail

STACK_NAME="CorpusQueryStack"
PROFILE=""
REGION=""

usage() {
  cat <<'EOF'
Fetch CDK stack outputs and create frontend/.env.local

Usage:
  ./scripts/create-env-local.sh [options]

Options:
  --stack-name <name>    CloudFormation stack name (default: CorpusQueryStack)
  --profile <profile>    AWS profile to use
  --region <region>      AWS region override
  -h, --help             Show this help text
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --stack-name) STACK_NAME="${2:-}"; shift 2 ;;
    --profile) PROFILE="${2:-}"; shift 2 ;;
    --region) REGION="${2:-}"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown argument: $1" >&2; usage; exit 1 ;;
  esac
done

# Check required CLI tools
for cmd in aws; do
  if ! command -v "$cmd" >/dev/null 2>&1; then
    echo "Error: required command '$cmd' is not available in PATH." >&2
    exit 1
  fi
done

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# Verify AWS credentials
echo "Verifying AWS credentials..."
if ! aws sts get-caller-identity ${PROFILE:+--profile "$PROFILE"} ${REGION:+--region "$REGION"} >/dev/null 2>&1; then
  echo "Error: AWS credentials not configured or expired." >&2
  echo "Run 'aws configure' or set AWS_ACCESS_KEY_ID/AWS_SECRET_ACCESS_KEY." >&2
  exit 1
fi

run_aws() {
  local args=()
  [[ -n "$PROFILE" ]] && args+=(--profile "$PROFILE")
  [[ -n "$REGION" ]] && args+=(--region "$REGION")
  aws "${args[@]}" "$@"
}

get_stack_output() {
  local key="$1"
  local value
  if ! value="$(run_aws cloudformation describe-stacks \
    --stack-name "$STACK_NAME" \
    --query "Stacks[0].Outputs[?OutputKey=='$key'].OutputValue | [0]" \
    --output text 2>/dev/null)"; then
    echo "Error: unable to read CloudFormation stack '$STACK_NAME'." >&2
    exit 1
  fi
  if [[ -z "$value" || "$value" == "None" ]]; then
    echo "Error: output '$key' not found in stack '$STACK_NAME'." >&2
    exit 1
  fi
  printf '%s' "$value"
}

echo "Fetching outputs from stack '$STACK_NAME'..."
API_URL="$(get_stack_output "ApiUrl")"
USER_POOL_ID="$(get_stack_output "UserPoolId")"
USER_POOL_CLIENT_ID="$(get_stack_output "UserPoolClientId")"

# Determine AWS region
if [[ -n "$REGION" ]]; then
  AWS_REGION="$REGION"
elif [[ -n "$AWS_REGION" ]]; then
  AWS_REGION="$AWS_REGION"
else
  AWS_REGION="us-east-1"
fi

ENV_FILE="$PROJECT_ROOT/frontend/.env.local"

cat > "$ENV_FILE" <<EOF
# Generated by scripts/create-env-local.sh
# Stack: $STACK_NAME
VITE_API_URL=$API_URL
VITE_USER_POOL_ID=$USER_POOL_ID
VITE_USER_POOL_CLIENT_ID=$USER_POOL_CLIENT_ID
VITE_AWS_REGION=$AWS_REGION
EOF

echo "Created $ENV_FILE"
echo "  VITE_API_URL=$API_URL"
echo "  VITE_USER_POOL_ID=$USER_POOL_ID"
echo "  VITE_USER_POOL_CLIENT_ID=$USER_POOL_CLIENT_ID"
echo "  VITE_AWS_REGION=$AWS_REGION"
echo ""
echo "Run the frontend with:"
echo "  cd frontend && bun dev"
